require: rubocop-rspec

AllCops:
  Exclude:
    - '*.gemspec'
    - 'bin/**/*'
    - 'db/**/*'
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.7
  NewCops: enable

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

# Prevent false positives because we have fields named "subject"
RSpec/SubjectDeclaration:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

# Warn only for complexity-related metrics
Metrics/MethodLength:
  Severity: warning

Metrics/ClassLength:
  Severity: warning

Metrics/BlockLength:
  Severity: warning

Metrics/ModuleLength:
  Severity: warning

Metrics/PerceivedComplexity:
  Severity: warning

Metrics/CyclomaticComplexity:
  Severity: warning

Metrics/AbcSize:
  Severity: warning

RSpec/ExampleLength:
  Severity: warning
