require: rubocop-rspec

AllCops:
  Exclude:
    - '*.gemspec'
    - 'bin/**/*'
    - 'db/**/*'
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.7
  NewCops: enable

# Warn only for long lines
Layout/LineLength:
  Max: 120
  Severity: warning

# Use single-quoted strings where possible
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

# Prevent false positives because we have fields named "subject"
RSpec/SubjectDeclaration:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

# Allow long test blocks with multiple expectations
RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

# Warn only for complexity-related metrics
Metrics/MethodLength:
  Severity: warning

Metrics/ClassLength:
  Severity: warning

Metrics/BlockLength:
  Severity: warning

Metrics/ModuleLength:
  Severity: warning

Metrics/PerceivedComplexity:
  Severity: warning

Metrics/CyclomaticComplexity:
  Severity: warning

Metrics/AbcSize:
  Severity: warning
