inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - '*.gemspec'
    - 'bin/**/*'
    - 'db/**/*'
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
