inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  Exclude:
    - '*.gemspec'
    - 'bin/**/*'
    - 'db/**/*'
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.7
  NewCops: enable

# Use single-quoted strings where possible
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

# Prevent false positives because we have fields named "subject"
RSpec/SubjectDeclaration:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

# Allow long test blocks with multiple expectations
RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false