# frozen_string_literal: true

ENV['RAILS_ENV'] ||= 'test'

require 'debug'
require 'combustion'
Combustion.initialize! :action_controller, :action_view

require 'mods_display'
require 'stanford-mods'
require 'capybara'
require 'rspec/rails'

Dir["#{File.expand_path(__dir__)}/fixtures/*.rb"].sort.each { |file| require file }
# Load i18n test file.
# We don't have any reliable translations yet so this
# just make sure that we're handling i18n properly.
I18n.load_path += Dir["#{File.expand_path('..', __dir__)}/spec/test_fr.yml"]
I18n.backend.load_translations

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# This file is loaded via the .rspec file.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
  config.include Rails.application.routes.url_helpers
end
