name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rails_version: [8.0.2, 7.2.2.1]
        ruby: ["3.4"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: bundle install
        env:
          RAILS_VERSION: ${{ matrix.rails_version }}
      - name: Run tests
        run: bundle exec rake
        env:
          RAILS_VERSION: ${{ matrix.rails_version }}
