name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rails_version: ["7.0.8.4", "7.1.3.4"]
        ruby: ["3.2", "3.3"]
        include:
          - ruby: "3.1"
            rails_version: "7.0.8.4"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: bundle install
        env:
          RAILS_VERSION: ${{ matrix.rails_version }}
      - name: Run tests
        run: bundle exec rake
        env:
          RAILS_VERSION: ${{ matrix.rails_version }}
