name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rails_version: ['7.0.4.3']
        ruby: ['3.0', '3.1', '3.2']
        include:
          - ruby: '3.0'
            rails_version: '6.1.7.3'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
    - name: Run tests
      run: bundle exec rake
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
