name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rails_version: [5.2, '6.0', '6.1', '7.0']
        ruby: [2.7, '3.0']
        exclude:
          - ruby: '3.0'
            rails_version: 5.2
          - ruby: '3.0'
            rails_version: '6.0'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
    - name: Run tests
      run: bundle exec rake
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
